component_depth: 1
languages:
- java
exclude:
- ./bin/.*
- ./build/.*
- ./build/internal/.*
- ./build/net/.*
- ./build/releases/.*
- ./build/site/.*
- ./build/site/xdoc/.*
- ./build/test/.*
- ./build/test/net/.*
- ./docs/.*
- ./docs/apidocs/.*
- ./docs/apidocs/net/.*
- ./docs/cgi/.*
- ./docs/images/.*
- ./docs/images/logos/.*
- ./docs/rules/.*
- ./docs/style/.*
- ./docs/xref/.*
- ./docs/xref/net/.*
- ./docs/xref-test/.*
- ./docs/xref-test/test/.*
- ./docs/xref-test/test/net/.*
- ./etc/.*
- ./etc/fr_docs/.*
- ./etc/grammar/.*
- ./etc/jsl/.*
- ./etc/xslt/.*
- ./java14/.*
- ./java14/bin/.*
- ./java14/lib/.*
- ./lib/.*
- ./regress/.*
- ./regress/test/.*
- ./regress/test/net/.*
- ./rulesets/.*
- ./rulesets/internal/.*
- ./rulesets/releases/.*
- ./xdocs/.*
- ./xdocs/cgi/.*
- ./xdocs/images/.*
